version: "3.8"

volumes:
  database:
    driver: 'local'

services:

  database:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    volumes:
      - database:/var/lib/mssql/data
    environment:
      MSSQL_SA_PASSWORD: "S3i4a7_kB"
      MSSQL_PID: "Developer"
      ACCEPT_EULA: "Y"