version: "3.8"

volumes:
  database:
    driver: 'local'

services:

  database:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    volumes:
      - database:/var/lib/mssql/data
    environment:
      SA_PASSWORD: "admin"
      ACCEPT_EULA: "Y"